Feature/tip
MixinNetwork/ios-app pull request #1096
Opened 2022-08-31 12:45 UTC by wuyuehyang

2022-09-15 06:44 UTC, SeniorZhai requested changes

2022-09-15 06:44 UTC, SeniorZhai commented on MixinServices/MixinServices/Services/Crypto/TIP/TIP.swift
> +                AppGroupKeychain.ephemeralSeed = seed
same as [it](https://github.com/MixinNetwork/ios-app/pull/1096#pullrequestreview-1108582327)

2022-09-15 07:46 UTC, wuyuehyang commented on MixinServices/MixinServices/Services/Crypto/TIP/TIP.swift
> +        LoginManager.shared.setAccount(account)
Fixed in [9bae6ae](https://github.com/MixinNetwork/ios-app/pull/1096/commits/9bae6aec973a7582adfd8e5ff53740b47fc078af)

2022-09-27 15:09 UTC, over140 approved these changes

2022-09-27 15:42 UTC, crossle approved these changes

2022-09-28 04:22 UTC, SeniorZhai approved these changes

2022-09-28 05:39 UTC, merged