Feature/screen lock
MixinNetwork/ios-app pull request #695
Opened 2021-06-16 06:56 UTC by fanyu

2021-06-18 19:16 UTC, wuyuehyang commented on Mixin/Constants/Localized.swift
> +            return R.string.localizable.setting_screen_lock_timeout_minutes("\(Int(seconds / 60))")        }
Code style

2021-06-18 19:28 UTC, wuyuehyang requested changes

2021-06-18 19:28 UTC, wuyuehyang commented on Mixin/UserInterface/Controllers/Common/ScreenLock/ScreenLockManager.swift
> +    private var hasLastBiometricAuthenticationFailed = false
Can these two variables `validAfterLastAuthentication` and `hasLastBiometricAuthenticationFailed` be merged into one?

2021-06-18 19:28 UTC, wuyuehyang commented on Mixin/UserInterface/Controllers/Setting/PrivacyViewController.swift
> +    private func screenLockTimeoutInterval() -> String {
Use `var` instead of `func` for non-heavy loaded works which takes no argument

2021-06-18 19:28 UTC, wuyuehyang commented on Mixin/Constants/Localized.swift
> +            return R.string.localizable.setting_screen_lock_timeout_minutes("\(Int(seconds / 60))")        }
Code style

2021-06-27 19:23 UTC, over140 approved these changes

2021-06-28 03:40 UTC, wuyuehyang approved these changes

2021-06-28 03:45 UTC, merged